### ISSUE TITLE
403 

### ISSUE THREAD

**Issue by keroum** [Kai0205/Get-link-server-Google#1]
The script is not working :(

**Comment by Kai0205** [comment]
Google fix 2016/10/11, I have yet to figure out how to fix it

**Comment by keroum** [comment]
123movies.to seems to have fixed it, they generate a new redirector link that has app=explorer instead of texmex

**Comment by Kai0205** [comment]
I will charge a fee for this
contact skype: kaiyukipro

**Comment by keroum** [comment]
OK go skype I have added you

**Comment by Kai0205** [comment]
Skype name ?

**Comment by keroum** [comment]
cinemacom1
